jdbc_url: jdbc:mysql://120.27.100.98:3306/iHelin
jdbc_user: root
jdbc_password: 246260
jdbc_driver: com.mysql.jdbc.Driver

admin_user: admin
admin_password: 246260

domain_url: https://www.520lyx.cn
system_name: Ian He

# 安工大助手
#wx_appId: wx9d6b26495bf4ee5c
#wx_appSecret: 26c55ea85c7924f05c3def29244c275c

# 测试
wx_appId: wx2bc2718db9216693
wx_appSecret: 78bbcdc96727e0d539bd6e08fb289a87